/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logicgamesfinalproject;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author coope
 */
public class DifficultyLevel extends javax.swing.JFrame {
    private int gameNum;
    private enum diff{EASY ,MEDIUM, HARD};
    private diff difficulty;
    private Player p;
    
    /**
     * Creates new form DifficultyLevel
     */
    public DifficultyLevel(int gameNum) {
        initComponents();
        this.gameNum=gameNum;
        p=Player.getPlayer();
    }
    
    private void createGame(int game, diff difficulty) throws IOException{
        int gridSize=0;
        MineSweeperCells[][] msCells=null;
        MemoryCells[][] memCells=null;
        p.setCurrentGame(game-1);
        
        
        //alter game board
        if(game==1){
            p.setGamesPlayed(p.getGamesPlayed(game-1)+1, game-1);
            p.saveStats();
            int numMines=0;
            if(difficulty==diff.EASY){
                gridSize=7;
                numMines=15;
            }
            else if(difficulty==diff.MEDIUM){
                gridSize=9;
                numMines=35;
            }
            else if(difficulty==diff.HARD){
                gridSize=12;
                numMines=55;
            }
            msCells= MineSweeperCells.makeGrid(gridSize);
            MineSweeperCells.placeMines(msCells, numMines);
            MineSweeperCells.findAdjMines(msCells);
            
        }
        else if(game==2 || game==3){
            p.setGamesPlayed(((p.getGamesPlayed(game-1))+1), game-1);
            p.saveStats();
            boolean pokemon=false;
            if(difficulty==diff.EASY){
                gridSize=4;
            }
            else if(difficulty==diff.MEDIUM){
                gridSize=6;
            }
            else if(difficulty==diff.HARD){
                gridSize=8;
            }
            if(game==3){
                pokemon=true;
            }
            memCells= MemoryCells.makeGrid(gridSize);
            MemoryCells.memoryCellValues(memCells, gridSize, pokemon);
            MemoryCells.setMoves(((gridSize*gridSize)/2)+(gridSize/2));
            if(game==3){
                MemoryCells.setPoke(true);
            }
        }
        //use the math for the cells to figure out where the mouse is clickedd
        
        //create game win
        GameWin g= new GameWin(memCells, msCells);
        g.setVisible(true);
        
        if(game==2 || game==3){
            g.hideFlagBtn();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDifficulty = new javax.swing.JLabel();
        btnEasy = new javax.swing.JButton();
        btnMedium = new javax.swing.JButton();
        btnHard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Difficulty Select");

        lblDifficulty.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblDifficulty.setText("Select Difficulty");

        btnEasy.setBackground(new java.awt.Color(153, 255, 153));
        btnEasy.setFont(new java.awt.Font("Segoe UI Historic", 2, 14)); // NOI18N
        btnEasy.setText("Easy");
        btnEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEasyActionPerformed(evt);
            }
        });

        btnMedium.setBackground(new java.awt.Color(255, 255, 51));
        btnMedium.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        btnMedium.setText("Medium");
        btnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumActionPerformed(evt);
            }
        });

        btnHard.setBackground(new java.awt.Color(255, 51, 51));
        btnHard.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnHard.setText("Hard");
        btnHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDifficulty))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMedium)
                            .addComponent(btnEasy)
                            .addComponent(btnHard))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDifficulty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEasy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEasyActionPerformed
        try {
            // TODO add your handling code here:
            difficulty=diff.EASY;
            createGame(gameNum, difficulty);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(DifficultyLevel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEasyActionPerformed

    private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed
        try {
            // TODO add your handling code here:
            difficulty=diff.MEDIUM;
            createGame(gameNum, difficulty);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(DifficultyLevel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMediumActionPerformed

    private void btnHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardActionPerformed
        try {
            // TODO add your handling code here:
            difficulty=diff.HARD;
            createGame(gameNum, difficulty);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(DifficultyLevel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DifficultyLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DifficultyLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DifficultyLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DifficultyLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEasy;
    private javax.swing.JButton btnHard;
    private javax.swing.JButton btnMedium;
    private javax.swing.JLabel lblDifficulty;
    // End of variables declaration//GEN-END:variables
}
