/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.logicgamesfinalproject;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author coope
 */
public class GameBoard extends javax.swing.JPanel{
    private int rectx=50;
    private int recty=50;
    
    private BoardCell[][] cells;
    /**
     * Creates new form GameBoard
     */
    public GameBoard() {
        initComponents();
        
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        
        Graphics2D g2= (Graphics2D)g;
        if(cells!=null){
            for (int i=0; i<cells.length; i++) {
                for(int j=0; j<cells[i].length; j++){
                    if (cells[i][j].showing==false){
                        g2.setColor(Color.black);
                        g2.fillRect(cells[i][j].cellx, cells[i][j].celly, BoardCell.cellw, BoardCell.cellh);
                    }
                    g2.setColor(Color.gray);
                    g2.drawRect(cells[i][j].cellx, cells[i][j].celly, BoardCell.cellw, BoardCell.cellh);
                }

            }

        }

        g2.drawRect(rectx, recty, 50, 50);
    }
    

    public void getCells(BoardCell[][] cells){
        this.cells=cells;
    }
    
    public void left(){
        rectx=rectx-30;
        repaint();
    }
        public void right(){
        rectx=rectx+30;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        int mouseX=evt.getX();
        int mouseY=evt.getY();
        double boardX=mouseX/BoardCell.cellw;
        double boardY=mouseY/BoardCell.cellh;
        boardX=Math.floor(boardX);
        boardY=Math.floor(boardY);
        int arrayIndexX=(int)boardX;
        int arrayIndexY=(int)boardY;
        
        cells[arrayIndexX][arrayIndexY].showing=true;
        
        repaint();
        
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
