/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logicgamesfinalproject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author coope
 */
public class GameSelectWin extends javax.swing.JFrame {
    private Player p;


            

    /**
     * Creates new form GameSelectWin
     */
    public GameSelectWin(String userName) {
        initComponents();
        btnStats.setIcon(new javax.swing.ImageIcon("src\\main\\images\\stats.png"));
        
        this.lblUser.setText(userName);
        p = Player.getPlayer();
        p.setName(userName);
        Player.getStats(p);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGameSelect = new javax.swing.JLabel();
        btnMineSweeper = new javax.swing.JButton();
        btnMemory = new javax.swing.JButton();
        lblCurrentUser = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnStats = new javax.swing.JButton();
        lblStats = new javax.swing.JLabel();
        btnPokeMemory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Select");
        setBackground(new java.awt.Color(255, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(153, 0, 0));
        setResizable(false);

        lblGameSelect.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblGameSelect.setText("Select a game");

        btnMineSweeper.setBackground(new java.awt.Color(255, 153, 153));
        btnMineSweeper.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnMineSweeper.setText("Mine Sweeper");
        btnMineSweeper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMineSweeperActionPerformed(evt);
            }
        });

        btnMemory.setBackground(new java.awt.Color(153, 255, 153));
        btnMemory.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnMemory.setText("Memory");
        btnMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryActionPerformed(evt);
            }
        });

        lblCurrentUser.setFont(new java.awt.Font("Segoe UI Variable", 2, 14)); // NOI18N
        lblCurrentUser.setText("Current User:");

        lblUser.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        btnStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatsActionPerformed(evt);
            }
        });

        lblStats.setFont(new java.awt.Font("Segoe UI Variable", 2, 14)); // NOI18N
        lblStats.setText("User Stats");

        btnPokeMemory.setBackground(new java.awt.Color(255, 255, 153));
        btnPokeMemory.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPokeMemory.setText("PokeMemory");
        btnPokeMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokeMemoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMineSweeper)
                        .addGap(18, 18, 18)
                        .addComponent(btnMemory)
                        .addGap(18, 18, 18)
                        .addComponent(btnPokeMemory)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGameSelect)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStats, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCurrentUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblStats)))
                    .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lblGameSelect)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMineSweeper)
                    .addComponent(btnMemory)
                    .addComponent(btnPokeMemory))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMineSweeperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMineSweeperActionPerformed
        // TODO add your handling code here:
        DifficultyLevel diffLev= new DifficultyLevel(1);
        diffLev.setVisible(true);

        
    }//GEN-LAST:event_btnMineSweeperActionPerformed

    private void btnMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryActionPerformed
        // TODO add your handling code here:
        DifficultyLevel diffLev= new DifficultyLevel(2);
        diffLev.setVisible(true);

    }//GEN-LAST:event_btnMemoryActionPerformed

    private void btnStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatsActionPerformed
        // TODO add your handling code here:
        UserStatsWin stats;
        DefaultTableModel dtmStats;
        stats=new UserStatsWin();
        Player.getStats(p);
        for(int i=0; i<Player.gameList.length; i++){
            stats.dtmStats.addRow(p.toString(i).split("\\|"));
        }
        stats.setVisible(true);
    }//GEN-LAST:event_btnStatsActionPerformed

    private void btnPokeMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokeMemoryActionPerformed
        // TODO add your handling code here:
        DifficultyLevel diffLev= new DifficultyLevel(3);
        diffLev.setVisible(true);
    }//GEN-LAST:event_btnPokeMemoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSelectWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSelectWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSelectWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSelectWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameSelectWin().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameSelectWin().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMemory;
    private javax.swing.JButton btnMineSweeper;
    private javax.swing.JButton btnPokeMemory;
    private javax.swing.JButton btnStats;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JLabel lblGameSelect;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
