/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.logicgamesfinalproject;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author coope
 */
public class GameBoard extends javax.swing.JPanel {
    private int rectx=50;
    private int recty=50;
    
    private BoardCell[] cells;
    /**
     * Creates new form GameBoard
     */
    public GameBoard() {
        initComponents();
        
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        
        Graphics2D g2= (Graphics2D)g;
        for (int i=0; i<cells.length; i++) {
            g2.drawRect(cells[i].cellx, cells[i].celly, cells[i].cellw, cells[i].cellh);
        }
        g2.drawRect(rectx, recty, 50, 50);
    }
    public void getCells(BoardCell[] cells){
        this.cells=cells;
    }
    
    public void left(){
        rectx=rectx-30;
        repaint();
    }
        public void right(){
        rectx=rectx+30;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
