/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logicgamesfinalproject;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author coope
 */
public class GameWin extends javax.swing.JFrame implements Updatable {
    private MemoryCells[][] memoryCells;
    private MineSweeperCells[][] mineSweeperCells;
    private int actions;
    private long startTime;
    private Player p;
    
    /**
     * Creates new form MineSweeperWin
     */
    public GameWin(MemoryCells[][] memoryCells, MineSweeperCells[][] mineSweeperCells) {
        initComponents();
        btnHome.setIcon(new javax.swing.ImageIcon("src/main/images/home.png"));
        btnMineFlag.setIcon(new javax.swing.ImageIcon("src/main/images/bigFlag.png"));
        p=Player.getPlayer();
        startTime=System.currentTimeMillis();
        this.memoryCells=memoryCells;
        this.mineSweeperCells=mineSweeperCells;
        //try makin two boards and disable the unused one
        gameBoard.getCells(mineSweeperCells, memoryCells);
        if(mineSweeperCells!=null){
            MineSweeperCells.setNumFlags(MineSweeperCells.numMinesInGrid);
            actions=MineSweeperCells.getNumFlagsRemaining();
            lblMovesRemaining.setText("Flags Left");
            gameBoard.setPreferredSize(new Dimension((mineSweeperCells.length*BoardCell.cellw), (mineSweeperCells.length*BoardCell.cellh)));
        }
        else{
            actions=MemoryCells.getMoves();
            gameBoard.setPreferredSize(new Dimension((memoryCells.length*BoardCell.cellw), (memoryCells.length*BoardCell.cellh)));
        }
        lblMoves.setText(String.valueOf(actions));
        gameBoard.addUpdatable(this);
    }
    @Override
    public void update(boolean lose){
        this.setVisible(false);
    }
    
    @Override
    public void update(int actionsLeft){
        actions=actionsLeft;
        lblMoves.setText(String.valueOf(actions));
    }
    
    @Override
    public void update(boolean win, Player p, int gameNum){
        if(win){
            p.setGamesWon(p.getGamesWon(gameNum)+1, gameNum);
            p.saveStats();
            JOptionPane.showMessageDialog(null, "You Win!!!", "Great Job!",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }
    
    @Override
    public void appendGameInfo(String text){
        long currTime=System.currentTimeMillis();
        long timeFromStart=currTime-startTime;
        int timeInSecs=(int) timeFromStart/1000;
        jtaGameInfo.setText(timeInSecs+": "+text);
    }
    
    @Override
    public void flagPressed(boolean flag){
        if(flag){
            btnMineFlag.setBackground(Color.BLACK);
        }
        else{
            btnMineFlag.setBackground(Color.WHITE);
        }
        
    }
    
    @Override
    public void cancelGame(){
        this.setVisible(false);
        p.setGamesPlayed(p.getGamesPlayed(p.getCurrentGame())-1, p.getCurrentGame());
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMineFlag = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        gameBoard = new com.mycompany.logicgamesfinalproject.GameBoardPanel();
        lblMovesRemaining = new javax.swing.JLabel();
        lblMoves = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaGameInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Game Window");

        btnMineFlag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMineFlagActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(102, 102, 102));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameBoardLayout = new javax.swing.GroupLayout(gameBoard);
        gameBoard.setLayout(gameBoardLayout);
        gameBoardLayout.setHorizontalGroup(
            gameBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        gameBoardLayout.setVerticalGroup(
            gameBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        lblMovesRemaining.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        lblMovesRemaining.setText("Moves Remaining");

        lblMoves.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        jtaGameInfo.setColumns(20);
        jtaGameInfo.setRows(5);
        jScrollPane1.setViewportView(jtaGameInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMineFlag))
                    .addComponent(gameBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMovesRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMoves)
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHome)
                        .addComponent(lblMoves))
                    .addComponent(lblMovesRemaining))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMineFlag))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnMineFlagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMineFlagActionPerformed
        // TODO add your handling code here:
        gameBoard.flagChange();
    }//GEN-LAST:event_btnMineFlagActionPerformed

    
    public void hideFlagBtn(){
        btnMineFlag.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMineFlag;
    private com.mycompany.logicgamesfinalproject.GameBoardPanel gameBoard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaGameInfo;
    private javax.swing.JLabel lblMoves;
    private javax.swing.JLabel lblMovesRemaining;
    // End of variables declaration//GEN-END:variables
}
